# alacritty/colors.toml
# THEME: Sunset

# Primary colors
[colors.primary]
background = "#17161A"
foreground = "#eeeefe"
dim_foreground = "#dedeee"
bright_foreground = "#fefeff"

# Cursor colors
[colors.cursor]
text = "#000000"
cursor = "#eeeefe"

# Normal colors
[colors.normal]
black = "#333339"
red = "#E0ABBE"
green = "#EBB894"
yellow = "#FAF9D2"
blue = "#B2C0EB"
magenta = "#E2B2EB"
cyan = "#9E82C4"
white = "#dddded"

# Bright colors
[colors.bright]
black = "#333339"
red = "#E0ABBE"
green = "#EBB894"
yellow = "#FAF9D2"
blue = "#B2C0EB"
magenta = "#E2B2EB"
cyan = "#9E82C4"
white = "#dddded"

# Selection colors
[colors.selection]
text = "#000000"
background = "#eeeefe"
